### ISSUE TITLE
More editor font size options

### ISSUE THREAD

**Issue by ghost** [RaitaroH/Stylus-DeepDark#32]
It's better if the range didn't start from 14px. I use 12px so had to edit the style. Just throwing it out there.

**Comment by the-j0k3r** [comment]
@Flanster thanks for the feedback.

I decided to simply remove the dropdown choices and use a custom text box. By default it has 12px as per Stylus default, this is more flexible because it will support all spec values like https://developer.mozilla.org/en-US/docs/Web/CSS/font-size describes.

On my original test for this change, I found it may break backwards compatibility because the custom entry was the old value `Large 14px` for me and `Large 14px` is invalid.

So Ill add this, with this caution and will bump the minor version, to reflect this possibility.
